### ISSUE TITLE
Ruby Testing

### ISSUE THREAD

**Issue by stephensli** [stephensli/cars#20]

**Comment by Maufa42** [comment]
@stephensli I would love to resolve this 🐛issue.
possibly will find some good 🖋️ solution.
It would be kind if you assign this to me.

**Comment by stephensli** [comment]
@Maufa42 thank you for being interested this ticket! I have yet to correctly scope out how I want to test this or have any related documentation to allow you to easily configure the application locally. This means it will be pretty hard to test this in a way that will be good!.

Here is the plan:

1. I'm going to get some documentation up once I have the sample site #6 complete.
2. I'll write some structured tests for a language outside of Ruby to allow you to see how I would like tests to be actioned

This should allow you to easily setup the repository locally, write new tests and get them in! If you give me a couple of days I'll let you know.

**Comment by Maufa42** [comment]
@stephensli Sounds Great👍 . Let's Do This Together
